d4l-data4life/js-sdk

.github/workflows/publish.yml

Currently the publish action tries to publish everytime a new commit is on master. This PR changes this and only publishes when the version actually changed. Therefore the github actions don't fail on master, even if the version was not increased

:construction_worker: Only try to publish when version changed

---

package-lock.json
package.json
src/config/index.js
src/d4l.js
src/lib/taggingUtils.ts
src/services/appDataService.ts
src/services/fhirService.ts
src/services/recordService.ts
test/services/appDataServiceTest.js
test/services/fhirServiceTest.js

This adds support for storing any form of data in the SDK. This data will not be checked at all and just packaged in the record metadata, encrypted and sent to the backend. It is tagged "flag=appdata", which is also used for the fetch operations for it.
Possible todo: avoid accidental downloading of appdata when calling the `fetchResources` function without any resourceType functions. Possbility is to detect a case and then Promise.all all supported version tags (appdata won't have any) or supported fhir resources (appdata won't have any).
https://gesundheitscloud.atlassian.net/browse/HUB-901
Describe how to inspect and verify your changes.

✨ ⬆️ HUB-901 add 'appData' support - CRUD methods for piping non-Fhir data through the SDK

---

package-lock.json
package.json
src/services/fhirService.ts
src/services/recordService.ts
test/services/appDataServiceTest.js
test/services/fhirServiceTest.js
test/services/recordServiceTest.js
test/testUtils/testVariables.js

- as discussed in slack: `exclude_tags` need to be encrypted
- I also opened a PR in phdp-records to make the tags be combined with `or` (merged now)
Describe how to inspect and verify your changes.

🐛 Encrypt exclude_tags parameter

---

package-lock.json
package.json

I updated the rollup-plugin-terser package as it depended on a highly vulnerable version of serialize-javascript.

:arrow_up: :lock: remove serialize-javascript vulnerability

---

docs/sdk.md
package-lock.json
package.json
src/lib/fhirValidator.ts
src/services/fhirService.ts
test/lib/fhirValidatorTest.ts
test/lib/models/fhir/documentReferenceTest.ts
test/services/fhirServiceTest.ts
test/services/recordServiceTest.ts
test/testUtils/r4FhirResources.ts
test/testUtils/recordResources.ts
test/testUtils/stu3FhirResources.ts
test/testUtils/testVariables.ts

This cleans up a few issues that came up after the release of 3.0.0 (and before).
For once, while we have employed AJV for its validation for a while, getting the actual errors has always been difficult and required either custom local SDK builds or step-by-step debugging in the browser. No more! We now directly **pass through a well-formatted list of all the validation woes**.
Furthermore, in the past we sent the original resource that was sent to `createResource` to the validator and we were fairly lucky that didn't bite us. However, documentReferences in R4 for instance don't actually support any additional properties such as the file property that we strip off the resource later in the process, so the validation would fail. As a solution, we now preemptively **sent a cleaned version …

✅ 🎨📝 ⬆️ R4 clarifications, improved validation

---

package-lock.json
package.json
src/services/fhirService.ts

With #27, we adapted the validation in the `create` method to validate against a cleaned version without attachments that we handle later, but that would break validation. This PR does the same for the `update` call.

🐛 validate against cleaned resources for update calls as well

---

.github/workflows/publish.yml
.github/workflows/test.yml
package-lock.json
package.json
src/services/appDataService.ts
src/services/fhirService.ts
src/services/recordService.ts
test/services/appDataServiceTest.ts
test/services/fhirServiceTest.ts
test/services/recordServiceTest.ts
test/testUtils/recordResources.ts

This aligns the behaviour of the JS SDK with the one for the other SDKs. When updating an entity (appData or fhirResource) that may contain tags, the following options are possible:
- do not supply tags: the original tags will be kept, plus any additions such an "updatedby" tag
- supply new tags: old tags will be removed and the new tags will be added, plus any additions such as an updatedby or resource tag
- supply an empty array as the tag parameter: old tags will be removed, no new tags will be added besides update/resource tags

✨🐛✅ delete existing tags/annotations when an update method supplies an empty array

---

package-lock.json
package.json
src/lib/fhirValidator.ts
test/lib/fhirValidatorTest.ts

Resources can contain other resources, but those themselves cannot contain other resources. This PR adds a test in the validator (and a test) for this. 
Also fixes async tests for the validator.
https://skeptics.stackexchange.com/questions/23913/is-this-a-ship-shipping-ship-shipping-shipping-ships

✨ ✅ check for resources containing containers

---

package-lock.json
package.json
src/services/fhirService.ts
test/services/fhirServiceTest.ts

When we upload the a resource during its updating process, it is being cleaned of its actual attachment file contents as those do not go to the FHIRService, but are uploaded in the DocumentService. We also use a cleaned version for the validation, though that had been based on a deepCloned version of the resource already.
However, cleanResource _mutates_ its parameter resource when deleting attachments, which is not only kind-of-meh design-wise, but will also throw an error in case we are given immuable objects for this operation. In order to fix this, we know perform this on deepclone of the parameter. Added tests for both cases.
Describe how to inspect and verify your changes.

🐛 fix bug where cleanResource would mutate an incoming resource

---

package-lock.json
package.json
src/lib/models/fhir/DocumentReference.ts
test/lib/models/fhir/documentReferenceTest.ts
test/testUtils/stu3FhirResources.ts

This fixes a bug where creating an DocumentReference with a `.fromFhirResource` method where the author was not set would crash. This hardens against the case, returning an undefined author instead. Also notices users that we plan to remove the method at one point.

🐛 fix a bug where an undefined author prop would crash

---

docs/sdk.md
package-lock.json
package.json
src/lib/taggingUtils.ts
src/services/appDataService.ts
src/services/fhirService.ts
src/services/types.ts
test/services/fhirServiceTest.ts

This adds support for querying the fhirversion of a document directly in fetch/count resources calls. It will be converted to a tag and queried as such, including the legacy format without the %2e encoding of the dots in a version number.
https://gesundheitscloud.atlassian.net/browse/SDK-524

✨ add support for querying by fhir version, including fallback for unencoded version

---

package-lock.json
package.json
src/lib/attachmentUtils.ts
src/lib/d4lRequest.ts
src/lib/models/fhir/DocumentReference.ts
src/services/attachmentService.ts
src/services/fhirService.ts
src/services/userService.ts
test/lib/models/fhir/documentReferenceTest.ts
test/services/attachmentServiceTest.ts
test/services/fhirServiceTest.ts
test/services/recordServiceTest.ts

This brings back the original pull request https://github.com/gesundheitscloud/hc-sdk-js/pull/375
As written back then:
This fixes an issue where documents created on the native apps where an attachment was deleted would not reload in the apps because the type was set to an empty string whereas it should be an empty object.
https://gesundheitscloud.atlassian.net/browse/SDK-453

🐛 ✅ SDK-453 fix invalid payload deleting attachments from native apps

---

src/services/recordService.ts
test/services/recordServiceTest.ts

When updating a FHIR record the `fhirversion=<FHIR-VERSION>` tag was not set correctly.

🐛 NAT-829 When updating a FHIR record the FHIR version tag was missing

---

docs/sdk.md
package-lock.json
package.json
src/services/fhirService.ts
src/services/recordService.ts
src/services/types.ts
test/services/recordServiceTest.ts

https://gesundheitscloud.atlassian.net/browse/SDK-613
Implement use of the Record services `include_deleted`, `start_updated_date` and  `end_updated_date` query parameter.
Export the records `Status` field to enable differentiation between active and deleted records.
Notes:
- There appeared to be lots of unused imports in `fhirService.ts` so I allowed my editor to clean that up.
Use `fetchResources` with the new parameter and see that deleted records are returned.

✨ SDK-613 HUB-1772 Fetch deleted records

---

package-lock.json
package.json
src/services/recordService.ts

Describe what you did in this pull request. If applicable, link to an issue here, such as 
https://gesundheitscloud.atlassian.net/browse/SDK-
- the records `updatedDate` was derived from the `createdAt` time of the record, which does not have the `Z` for the timezone at the end. Thus the frontend treated it as local time. But it is actually in UTC, as it is the same date as `updated`, but `updated` did have the timezone
Describe how to inspect and verify your changes.
- When you fetch all records via updatedDate and then take the most recent date to filter the next search you will never run out of records, since the updatedDate is 2 hours off due to timezone stuff (UTC vs +2)

🐛 Fix updatedDate being timezoneless

---

src/lib/stringUtils.ts
src/lib/taggingUtils.ts
test/lib/taggingUtilsTest.ts
test/services/fhirServiceTest.ts

Old iOS apps were tagging without lowercasing the percent encoding, so it's another case to add to the tags parameter when searching/counting.
https://gesundheitscloud.atlassian.net/browse/SDK-634

[SDK-634] Fix retrieval of old iOS apps documents

---

package-lock.json
package.json

Adress dependabot alert (https://github.com/advisories/GHSA-hj48-42vr-x3v9) and update to version 5.9.1

🔒🏷  Fix dependabot alert and update to version 5.9.1

---

docs/sdk.md
package-lock.json
package.json
src/lib/taggingUtils.ts
src/services/types.ts
test/services/fhirServiceTest.ts
test/services/recordServiceTest.ts

The backend supports AND gating and OR grouping:
> Multiple tags can be separated by comma for AND gating. Tags can be grouped together using round brackets for creating groups of OR conditions.
Even though the SDK (internally) already supported this, this PR exposes this feature to the enduser. OR groups can now be created by adding the annotations to an array:
```
{
...
annotations: [['tag1, 'tag2'], 'tag3'],
...
}
```
Using these annotations in a query, the result will include resources that are tagged with `tag1` OR `tag2` AND `tag3`.
For `exclude_tags` the logic is reversed.

✨ Support AND and OR for querying resources

---

docs/sdk.md
package-lock.json
package.json
src/d4l.ts

With this change it is possible to disable the regular (every 5min) polling of updates in the common keys. The default is to keep it enabled.
https://gesundheitscloud.atlassian.net/browse/HUB-2518

✨ Allow disabling of user info polling

---

package-lock.json
package.json
src/routes/keyRoutes.ts
src/routes/userRoutes.ts
src/services/userService.ts
test/routes/keyRoutesTest.ts
test/services/userServiceTest.ts
test/testUtils/keyResources.ts

The key management is being moved to a separate service and therefore we need to migrated to the new endpoints.
1. Run `npm run build`
2. Switch directory to `/dest`
3. Run `npm link`
4. Switch to the project which uses the JS-SDK
5. Use the linked version of the JS-SDK by running `npm link @d4l/js-sdk`
6. Run and test your project

♻️  HUB-2809 CIT-4600 CIT-4601 Use new key management service endpoints
